server:
  port: 9000

spring:
  application:
    name: demo

  profiles:
    include: real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc

demo:
  jwt-key: nU9dNrQG9jfmlZ8+EfdyCaMFzzegYpCcQyufQK+Ag4Q=