server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo # 변경해주세요
    username: root # username
    password: 0991 # password
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전